"""Change std_code from UUID to String

Revision ID: 0508267ef962
Revises: 5300fbacc8bf
Create Date: 2025-10-27 12:10:44.170203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0508267ef962'
down_revision: Union[str, Sequence[str], None] = '5300fbacc8bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Use raw SQL to convert UUID to VARCHAR with USING clause
    # This handles existing UUID values by converting them to text
    op.execute("""
        ALTER TABLE students 
        ALTER COLUMN std_code TYPE VARCHAR(255) 
        USING CASE 
            WHEN std_code IS NULL THEN NULL::VARCHAR
            ELSE std_code::text
        END
    """)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('students', 'std_code',
               existing_type=sa.String(length=255),
               type_=sa.UUID(),
               existing_nullable=True)
    # ### end Alembic commands ###
