"""add email and password to staff

Revision ID: 07cd554f3e20
Revises: 25c3f46f01b7
Create Date: 2025-10-24 10:43:51.836550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07cd554f3e20'
down_revision: Union[str, Sequence[str], None] = '25c3f46f01b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add columns as nullable
    op.add_column('staff', sa.Column('email', sa.String(length=255), nullable=True))
    op.add_column('staff', sa.Column('password', sa.String(length=255), nullable=True))
    
    # Update existing records with default values
    from utils.password_utils import hash_password
    import uuid
    
    # Get connection
    connection = op.get_bind()
    
    # Update existing staff records with default email and password
    result = connection.execute(sa.text("SELECT staff_id FROM staff"))
    for row in result:
        staff_id = row[0]
        default_email = f"staff_{staff_id}@school.com"
        default_password = hash_password("defaultpassword123")
        
        connection.execute(
            sa.text("UPDATE staff SET email = :email, password = :password WHERE staff_id = :staff_id"),
            {"email": default_email, "password": default_password, "staff_id": staff_id}
        )
    
    # Now make columns NOT NULL
    op.alter_column('staff', 'email', nullable=False)
    op.alter_column('staff', 'password', nullable=False)
    
    # Add unique constraint
    op.create_unique_constraint(None, 'staff', ['email'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='unique')
    op.drop_column('staff', 'password')
    op.drop_column('staff', 'email')
    # ### end Alembic commands ###
