"""add_unique_constraint_current_academic_year_per_school

Revision ID: 08001c2a3bfc
Revises: 4ffe3cea8a88
Create Date: 2025-10-24 12:04:19.512947

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08001c2a3bfc'
down_revision: Union[str, Sequence[str], None] = '4ffe3cea8a88'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add partial unique index to ensure only one current academic year per school
    op.create_index(
        'ix_academic_years_school_current_unique',
        'academic_years',
        ['school_id'],
        unique=True,
        postgresql_where=sa.text('is_current = true AND is_deleted = false')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove partial unique index
    op.drop_index('ix_academic_years_school_current_unique', 'academic_years')
    # ### end Alembic commands ###
