"""Update fee_management: add amount_paid, change status to string

Revision ID: 10bad0f199e2
Revises: 0508267ef962
Create Date: 2025-10-27 12:39:25.311178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10bad0f199e2'
down_revision: Union[str, Sequence[str], None] = '0508267ef962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fee_management', sa.Column('amount_paid', sa.Float(), nullable=False))
    op.alter_column('fee_management', 'status',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('fee_management', 'status',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               nullable=True)
    op.drop_column('fee_management', 'amount_paid')
    # ### end Alembic commands ###
