"""add_school_id_to_staff

Revision ID: 25c3f46f01b7
Revises: bde8cfb28f6a
Create Date: 2025-10-23 14:02:53.667871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c3f46f01b7'
down_revision: Union[str, Sequence[str], None] = 'bde8cfb28f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('staff', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_staff_school_id'), 'staff', ['school_id'], unique=False)
    op.create_foreign_key(None, 'staff', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_index(op.f('ix_staff_school_id'), table_name='staff')
    op.drop_column('staff', 'school_id')
    # ### end Alembic commands ###
