"""add_school_id_to_staff

Revision ID: 25c3f46f01b7
Revises: bde8cfb28f6a
Create Date: 2025-10-23 14:02:53.667871

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c3f46f01b7'
down_revision: Union[str, Sequence[str], None] = 'bde8cfb28f6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('staff', sa.Column('school_id', sa.UUID(), nullable=True))
    
    # Update existing staff records to have a default school_id (use first school if available)
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT school_id FROM schools WHERE is_deleted = false LIMIT 1"))
    first_school = result.fetchone()
    
    if first_school:
        default_school_id = first_school[0]
        connection.execute(
            sa.text("UPDATE staff SET school_id = :school_id WHERE school_id IS NULL"),
            {"school_id": default_school_id}
        )
    else:
        # If no schools exist, we can't set a valid school_id
        # Delete existing staff records as they can't exist without a school
        connection.execute(sa.text("DELETE FROM staff"))
    
    # Now make the column non-nullable
    op.alter_column('staff', 'school_id', nullable=False)
    
    op.create_index(op.f('ix_staff_school_id'), 'staff', ['school_id'], unique=False)
    op.create_foreign_key(None, 'staff', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'staff', type_='foreignkey')
    op.drop_index(op.f('ix_staff_school_id'), table_name='staff')
    op.drop_column('staff', 'school_id')
    # ### end Alembic commands ###
