"""Add amount_to_pay to fee_types

Revision ID: 2e6a9ff7ebc8
Revises: 10bad0f199e2
Create Date: 2025-10-27 12:50:25.804391

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e6a9ff7ebc8'
down_revision: Union[str, Sequence[str], None] = '10bad0f199e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add column with default value first
    op.add_column('fee_types', sa.Column('amount_to_pay', sa.Float(), nullable=True, server_default='0.0'))
    
    # Update existing rows to have default value
    op.execute("UPDATE fee_types SET amount_to_pay = 0.0 WHERE amount_to_pay IS NULL")
    
    # Make column NOT NULL
    op.alter_column('fee_types', 'amount_to_pay',
                    nullable=False,
                    server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fee_types', 'amount_to_pay')
    # ### end Alembic commands ###
