"""remove_unique_constraint_academic_years

Revision ID: 4fdd257c0774
Revises: 08001c2a3bfc
Create Date: 2025-10-24 12:08:41.992350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fdd257c0774'
down_revision: Union[str, Sequence[str], None] = '08001c2a3bfc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_academic_years_school_current_unique'), table_name='academic_years', postgresql_where='((is_current = true) AND (is_deleted = false))')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_academic_years_school_current_unique'), 'academic_years', ['school_id'], unique=True, postgresql_where='((is_current = true) AND (is_deleted = false))')
    # ### end Alembic commands ###
