"""add_unique_constraint_staff_id_teachers

Revision ID: 4ffe3cea8a88
Revises: f86c49cd50c8
Create Date: 2025-10-24 11:50:36.926890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ffe3cea8a88'
down_revision: Union[str, Sequence[str], None] = 'f86c49cd50c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add unique constraint on staff_id in teachers table
    op.create_unique_constraint('uq_teachers_staff_id', 'teachers', ['staff_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Remove unique constraint on staff_id in teachers table
    op.drop_constraint('uq_teachers_staff_id', 'teachers', type_='unique')
    # ### end Alembic commands ###
