"""add_classes_and_class_teachers_tables

Revision ID: 976118ff6cb3
Revises: e140290d4dea
Create Date: 2025-10-24 12:18:29.597542

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '976118ff6cb3'
down_revision: Union[str, Sequence[str], None] = 'e140290d4dea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if class_teachers table already exists
    connection = op.get_bind()
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'class_teachers'
        )
    """))
    table_exists = result.scalar()
    
    if not table_exists:
        op.create_table('class_teachers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('teacher_id', sa.UUID(), nullable=False),
        sa.Column('subj_id', sa.UUID(), nullable=False),
        sa.Column('cls_id', sa.UUID(), nullable=False),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('is_deleted', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['cls_id'], ['classes.cls_id'], ),
        sa.ForeignKeyConstraint(['subj_id'], ['subjects.subj_id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_class_teachers_id'), 'class_teachers', ['id'], unique=False)
    
    # Check if classes_to_teachers table exists and drop it if it does
    result = connection.execute(sa.text("""
        SELECT EXISTS (
            SELECT FROM information_schema.tables 
            WHERE table_schema = 'public' 
            AND table_name = 'classes_to_teachers'
        )
    """))
    old_table_exists = result.scalar()
    
    if old_table_exists:
        op.drop_index(op.f('ix_classes_to_teachers_id'), table_name='classes_to_teachers', if_exists=True)
        op.drop_table('classes_to_teachers')
    op.alter_column('classes', 'cls_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('classes', 'cls_manager',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('classes', 'cls_manager',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('classes', 'cls_type',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.create_table('classes_to_teachers',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('teacher_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('subj_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('cls_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('start_date', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cls_id'], ['classes.cls_id'], name=op.f('classes_to_teachers_cls_id_fkey')),
    sa.ForeignKeyConstraint(['subj_id'], ['subjects.subj_id'], name=op.f('classes_to_teachers_subj_id_fkey')),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], name=op.f('classes_to_teachers_teacher_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('classes_to_teachers_pkey'))
    )
    op.create_index(op.f('ix_classes_to_teachers_id'), 'classes_to_teachers', ['id'], unique=False)
    op.drop_index(op.f('ix_class_teachers_id'), table_name='class_teachers')
    op.drop_table('class_teachers')
    # ### end Alembic commands ###
