"""remove_unique_constraints_academic_years_keep_current_only

Revision ID: e140290d4dea
Revises: 4fdd257c0774
Create Date: 2025-10-24 12:11:28.777074

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e140290d4dea'
down_revision: Union[str, Sequence[str], None] = '4fdd257c0774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Ensure no unique constraints on individual columns
    # Keep only the partial unique index for current academic year per school
    
    # Check if there are any unique constraints on academic_name or other columns
    # and remove them if they exist (this is a safety measure)
    
    # The only unique constraint we want to keep is:
    # ix_academic_years_school_current_unique (partial unique index)
    # which ensures only one current academic year per school
    
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
