"""add_school_id_to_attendance

Revision ID: e8bd632669ab
Revises: 0721a7821927
Create Date: 2025-10-28 12:19:03.614079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8bd632669ab'
down_revision: Union[str, Sequence[str], None] = '0721a7821927'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students_attendance', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'students_attendance', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students_attendance', type_='foreignkey')
    op.drop_column('students_attendance', 'school_id')
    # ### end Alembic commands ###
