"""add_school_id_to_subjects

Revision ID: eafbb56cc22f
Revises: 976118ff6cb3
Create Date: 2025-10-24 13:19:13.292325

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eafbb56cc22f'
down_revision: Union[str, Sequence[str], None] = '976118ff6cb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('subjects', sa.Column('school_id', sa.UUID(), nullable=True))
    
    # Update existing subjects to have a default school_id (use first school if available)
    # For now, we'll delete existing subjects since they don't have school context
    op.execute("DELETE FROM subjects")
    
    # Now make the column non-nullable
    op.alter_column('subjects', 'school_id', nullable=False)
    
    op.create_index(op.f('ix_subjects_school_id'), 'subjects', ['school_id'], unique=False)
    op.create_foreign_key(None, 'subjects', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subjects', type_='foreignkey')
    op.drop_index(op.f('ix_subjects_school_id'), table_name='subjects')
    op.drop_column('subjects', 'school_id')
    # ### end Alembic commands ###
