"""add_school_id_to_academic_years

Revision ID: f86c49cd50c8
Revises: 07cd554f3e20
Create Date: 2025-10-24 11:27:53.081720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86c49cd50c8'
down_revision: Union[str, Sequence[str], None] = '07cd554f3e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First add the column as nullable
    op.add_column('academic_years', sa.Column('school_id', sa.UUID(), nullable=True))
    
    # Update existing records to have a default school_id
    connection = op.get_bind()
    result = connection.execute(sa.text("SELECT school_id FROM schools WHERE is_deleted = false LIMIT 1"))
    first_school = result.fetchone()
    
    if first_school:
        default_school_id = first_school[0]
        connection.execute(
            sa.text("UPDATE academic_years SET school_id = :school_id WHERE school_id IS NULL"),
            {"school_id": default_school_id}
        )
    else:
        # If no schools exist, delete existing academic years
        connection.execute(sa.text("DELETE FROM academic_years"))
    
    # Now make the column non-nullable
    op.alter_column('academic_years', 'school_id', nullable=False)
    
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_foreign_key(None, 'academic_years', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_column('academic_years', 'school_id')
    # ### end Alembic commands ###
