"""add_school_id_to_academic_years

Revision ID: f86c49cd50c8
Revises: 07cd554f3e20
Create Date: 2025-10-24 11:27:53.081720

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f86c49cd50c8'
down_revision: Union[str, Sequence[str], None] = '07cd554f3e20'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('academic_years', sa.Column('school_id', sa.UUID(), nullable=False))
    op.create_index(op.f('ix_academic_years_school_id'), 'academic_years', ['school_id'], unique=False)
    op.create_foreign_key(None, 'academic_years', 'schools', ['school_id'], ['school_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'academic_years', type_='foreignkey')
    op.drop_index(op.f('ix_academic_years_school_id'), table_name='academic_years')
    op.drop_column('academic_years', 'school_id')
    # ### end Alembic commands ###
